### ISSUE TITLE
Architectures Roadmap

### ISSUE THREAD

**Issue by ravidsrk** [androidstarters/androidstarters.com#2]
- [x] **Mindorks MVP** https://github.com/MindorksOpenSource/android-mvp-architecture
- [x] **Mindorks MVVM** https://github.com/MindorksOpenSource/android-mvvm-architecture
- [x] **Mindorks MVP Interactor** https://github.com/MindorksOpenSource/android-mvp-interactor-architecture
- [ ] **Just-Another-Android-App** https://github.com/athkalia/Just-Another-Android-App
- [ ] **AndroidTDDBootStrap** https://github.com/Piasy/AndroidTDDBootStrap
- [ ] **Basic MVP without Dagger**
- [ ] **Android Architecture Components**

**Comment by ditclear** [comment]
https://github.com/JessYanCoding/MVPArms
https://github.com/xiaobailong24/MVVMArms

**Comment by ravidsrk** [comment]
@ditclear, Looks like great suggestion. I will add these up by this weekend.

**Comment by ditclear** [comment]
great!very useful project for us。

**Comment by abalta** [comment]
Another great clean boilerplates by android10

https://github.com/android10/Android-CleanArchitecture-Kotlin
